### ISSUE TITLE
Not working with Lemmy Communities

### ISSUE THREAD

**Issue by maegul** [gugray/rss-parrot#14]
Tried using rss-parrot on a lemmy community RSS feed and nothing seems to be coming through the bot when I can confirm new posts have come through on an ordinary RSS app (eg, feedly).

The bot: https://rss-parrot.net/web/feeds/lemmy.ml.c.test
The lemmy community: https://lemmy.ml/c/test
Posts made since the bot was created that haven't been posted: https://lemmy.ml/post/10189784 https://lemmy.ml/post/10191680

The two posts above did come through on feedly.

**Comment by gugray** [comment]
I have no experience with Lemmy TBH and I've been focusing solely on Mastodon.
Could you try and see later today, when v0.0.36 goes live, if #2 has maybe fixed this?
If not, I'll need to look into this later.

**Comment by gugray** [comment]
OK, I had the chance to look intot this! Initially I believed this was a federation issue (i.e., a problem where you wanted to talk to the birb from Lemmy and receive posts via ActivityPub). Now I see this is "simply" about following the feed of a Lemmy community.

I looked into the page source of https://lemmy.ml/c/test. It declares an Atom feed like so: `<link rel="alternate" type="application/atom+xml" href="https://lemmy.ml/feeds/c/test.xml?sort=undefined">`

That is perfectly legit, but when I try to load it in a browser I get this error instead of the feed:  `{"error":"unknown","message":"Matching variant not found"}`

If I remove the query parameter and simply load https://lemmy.ml/feeds/c/test.xml, then I get the Atom feed back. I messaged the birb about it and it returned with the parrot account: https://rss-parrot.net/web/feeds/lemmy.ml.c.test
It seems to have been created a while ago already.

SUMMARY: It appears to me that the feed URL embedded in the community's page does not work. For now I'm marking this as "not an issue" from RSS Parrot's perspective, but LMK if I'm missing something!

**Comment by gugray** [comment]
I am considering removing any query parameters from feed URLs before retrieving them. AFAIK there is no standard convention about using query parameters here, and it seems to me they can be used to "multiply" feeds unnecessarily. Notably, I don't want four different accounts in the Parrot because the same feed can be retrieved ordered by ascending or decscending order, according to two different parameters...
