### ISSUE TITLE
Opting out

### ISSUE THREAD

**Issue by michaelnordmeyer** [gugray/rss-parrot#32]
I'd like to opt-out, because I believe creators should be in control who's publishing what and where. That means it should be opt-in, especially because it's not hard to create another fediverse account for just publishing their own feed.

I don't think opting out by e-mail is reasonable, because it exposes an otherwise not exposed e-mail address.

I also don't think putting a hashtag on a profile is reasonable, because it litters the profile with unrelated info and won't work for many "services".

Having the automatic feed account deleted is important to achieve a full opt-out, because I don't want a feed with my name on lingering around.

You can gather the feed in question from my GitHub profile.

**Comment by gugray** [comment]
Thanks for sharing your opinions, they've been duly noted.

I deleted the parrot account for the feed you are referring to, and added the feed to the blocklist.

I assume you already made changes on the server side, because before I deleted the account the birb's request for the feed was already rejected with a 406 response code. This way the content of your feed is double-secured from accidentally being retrieved again and shown to any unintended audience in the Fediverse.
