### ISSUE TITLE
Boost author's fedi post if available

### ISSUE THREAD

**Issue by Atemu** [gugray/rss-parrot#39]
This is a wild idea that popped to my head:

Would it be possible to detect whether the author of i.e. the blog post already shared it on their verified Fedi account and boost that post instead?

How I'd imagine this to work would be that the parrot would look for a Fedi verification link on the followed website and follow the author. If a new link appears in the website's feed, the parrot would check whether the author has mentioned the new link in a post of theirs.  
If they have, the parrot would boost that post. If they haven't, it would fall back on creating a new post of its own.

Now obviously, you'd have to wait a certain amount of time before checking as the author may need some time to type out the Fedi post.

This would allow me to boost the author's post that A. has their account linked to it and B. may provide better extra info such as a short summary.

(Why not follow the author directly? I usually don't want to see every single thing an author posts on their Fedi account in my feed but do want to see their higher effort articles.)

**Comment by gugray** [comment]
Thank you for sharing this! While I do like the idea in theory, implementing this would, without exaggeration, make the Parrot several times more complex than it currently is. I can sustain this project if/because it stays lean and laser-focused on doing a single thing a simple way.

I'm closing the issue as "won't fix".
