### ISSUE TITLE
https://tvl.fyi/feed.atom not recognised

### ISSUE THREAD

**Issue by Atemu** [gugray/rss-parrot#40]
```
[@Atemu@darmstadt.social](https://darmstadt.social/users/Atemu) Hm, I can't find a feed for this site.

Is the address right? It can also happen that the site is temporarily down, or it doesn't have a valid RSS or Atom feed.
```

**Comment by gugray** [comment]
The problem is that the feed doesn't link back to the website itself. The Parrot derives the account's name from the website's name, which is unknown if you request the feed.

It will work if you request the website itself like this: @birb@rss-parrot.net https://tvl.fyi/
In that case the Parrot already know the website address you're telling it, so it can derive a name for the account.
