### ISSUE TITLE
Use RSS enclosure as media attachment

### ISSUE THREAD

**Issue by geraldo** [gugray/rss-parrot#42]
Would be nice to have the possibility to attach media files, at least images would be a great feature. So this is a feature request for adding RSS enclosures as media attachments when sending out new toots.

**Comment by gugray** [comment]
Thank you for suggesting this! I will not implement this, because I don't see a way of doing it that is both safe and lets me keep the Parrot simple.

I would not be comfortable including external links to media in toots that my service sends out. This creates a vector that can be both abused to harm end users' devices, and to spread inappropriate content. It could be abused by people posting on the external feeds themsleves, but also by someone requesting an existing feed with inappropriate content. (The toots show up in the public timeline of Mastodon instances.)

The only way I would see this happening responsibly is if the Parrot itself retrieves the media, optimizes/compresses it, and links to its own copy in the toots. That, however, would mean:
- The need for active content moderation
- Significantly more compute/resources
- Potential trouble around intellectual property/copyright issues
