### ISSUE TITLE
Can't get feeds from SPIP CRM

### ISSUE THREAD

**Issue by yldun** [gugray/rss-parrot#46]
It seems every (French) feeds based on SPIP , an old French CRM, are not working.

For example :

[https://orientxxi.info](https://orientxxi.info) has a RSS flux here: [https://orientxxi.info/?page=backend&lang=fr
](https://orientxxi.info/?page=backend&lang=fr
)

Maybe related to this POST attributes.

**Comment by gugray** [comment]
This is an unfortunate consquence of the change here: https://github.com/gugray/rss-parrot/issues/14#issuecomment-1890476220

The Parrot removes all query parameters from the RSS feed's URL. The reason is because many sites allow an endless number of RSS feeds reflecting various sorted/filtered views of the same content, and this was polluting the feeds in the Parrot.

I'm adding exceptions to legit multi-user sites that have a legit URL template relying on query parameters, e.g., Youtube.

I am not willing to do this for a CRM that thinks putting the RSS feed under a ?page=backend is a good idea :( Please take it up with the CRM's developers! Any path works for the RSS or Atom feed as long as it doesn't depend on query parameters. E.g., /feed, /rss and /atom are all widespread and battle-tested options.
